- solutions/kubernetes/cluster-functions.sh
- Enable exception handing for daemon.json file update. 
> EOS-26146 Enable exception handing for daemon.json file update.

- jenkins/automation/kubernetes/setup-k8-cluster.groovy
- solutions/kubernetes/cluster-functions.sh
- Remove master word from Jenkins options. Fix issue with updating dameon.json, Corrected email notification. 
> EOS-26146 - Remove master word from Jenkins options and other improvements.

- jenkins/automation/kubernetes/cortx-all-image.groovy
- jenkins/deployment/k8s_deployment/cortx-cluster.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/provisioner.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/release.groovy
- K8s post-merge 1N and 3N pipeline jobs.
> EOS-26146 - K8s post-merge 1N and 3N pipeline jobs. 

- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
-  Enable SNS as 2+1+0 for Nightly 3N Build and Deploy pipeline
> EOS-26146 - Enable SNS as 2+1+0 for Nightly 3N Build and Deploy pipeline.

- jenkins/automation/kubernetes/cortx-all-image.groovy
- Improve image selection command while deleting old images. 
- [x ] JIRA number/GitHub Issue added to PR
> EOS-26146 - Improve image selection command.

- docker/cortx-deploy/Dockerfile
- docker/cortx-deploy/build.sh
- docker/cortx-deploy/opensource-ci/C7.9.2009.repo
- Fix for https://github.com/Seagate/cortx-re/issues/764
> EOS-26146 - Modified Dockerfile and build.sh for community support

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- Collecting Cortx Support Bundle as artifact in CI-CD Job
-  Added support for log collection of Collecting Cortx Support Bundle as artifact in CI-CD Job.
- http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/145/console
> EOS-26727: Collecting Cortx Support Bundle as artifact in CI-CD Job

- jenkins/custom-ci/centos-7.9.2009/provisioner.groovy
- Added fix to avoid custom build jenkins job failure for main branch custom-ci build.
> EOS-27074 - Custom build jenkins job for Cent OS 7.9 is failing.

- jenkins/internal-ci/centos-7.9.2009/branch/cortx-ha.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/cortx-py-utils.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/csm-agent.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/hare.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/motr.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/provisioner.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/s3server.groovy
- Print image name in the component email notification so that developers will know then image name. 
> EOS-27074 Print image name in component email notification

- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
- Update email notification list.
> EOS-26146 - Update email notification list.

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/io-testing.sh
- solutions/kubernetes/s3-client-setup.sh
- Clean-up pre-installed CORTX cluster as part of setup-cortx-cluster pipeline.
> EOS-26147 - Clean-up pre-installed CORTX cluster as part of setup-cortx-cluster pipeline

- docker/cortx-deploy/build.sh
- jenkins/automation/kubernetes/deploy-cortx-k8-cluster.groovy
- jenkins/automation/kubernetes/destroy-cluster.groovy
- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- jenkins/automation/kubernetes/setup-k8-cluster.groovy
- jenkins/automation/kubernetes/setup-minikube-cluster.groovy
- jenkins/automation/kubernetes/setup-third-party.groovy
- jenkins/automation/kubernetes/symas-openldap.groovy
- jenkins/deployment/k8s_deployment/cortx-cluster.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/release.groovy
- Switch kubernetes -> main branch
> EOS-26147 - Switch kubernetes -> main branch

- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
- solutions/kubernetes/cluster-functions.sh
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- Latest image is not getting pulled on worker nodes. Earlier prereq-deploy-cortx-cloud.sh used to pull images. It's not downloading now. Hence added explicit docker pull command. 
> EOS-26147 - Latest image is not getting pulled on worker nodes

- solutions/kubernetes/cortx-deploy-functions.sh
- Print docker images information as part of cluster status.
> EOS-26147 - Print docker images information as part of cluster status.

- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
- Use cortx-all image name from Jenkins parameters input
> EOS-27128 Use cortx-all image name from Jenkins parameters input

- solutions/kubernetes/cortx-deploy-functions.sh
- Added support for Release v0.0.17.
-  Added support for Release v0.0.17.
- 3 node: http://eos-jenkins.colo.seagate.com/job/Cortx-Kubernetes/job/setup-cortx-cluster-solution-input/212/console
- Single node: http://eos-jenkins.colo.seagate.com/job/Cortx-Kubernetes/job/setup-cortx-cluster-solution-input/213/console
- 3 node regular deployment: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/139/console
> EOS-26149: Added support for Release v0.0.17.

- docker/cortx-deploy/third-party-rpms.txt
- Remove kafka from cortx-all image
Generated custom-image as `cortx-docker.colo.seagate.com/seagate/cortx-all:kafka-removed-758` and tested single-node deployment using http://eos-jenkins.colo.seagate.com/job/Cortx-kubernetes/job/setup-cortx-cluster/1076/ 
> EOS-27287 cortx-all image - Remove kafka from cortx-all image

- jenkins/internal-ci/centos-7.9.2009/pr/cortx_deployment/csm_agent.groovy
- jenkins/internal-ci/centos-7.9.2009/pr/cortx_deployment/ha.groovy
- jenkins/internal-ci/centos-7.9.2009/pr/cortx_deployment/provisioner.groovy
- jenkins/internal-ci/centos-7.9.2009/pr/cortx_deployment/pyutils.groovy
- Enable PR based deployments on main branch
-  Added k8s based image generation and deployment job trigger in PR deployment groovy scripts.
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Kubernetes/job/provisioner/16/
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Kubernetes/job/csm-agent/20/
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Kubernetes/job/ha/13/
http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Kubernetes/job/py-utils/24/
> EOS-26968 : Update PR deployments

- solutions/kubernetes/cortx-deploy.sh
- solutions/kubernetes/io-testing.sh
- solutions/kubernetes/s3-client-setup.sh
Added IO sanity test error check.
- Add IO sanity test error check 
- Fix IO sanity test for solution_input job.
-  Added IO sanity test error check and update fixes for solution_input.
- 3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/161/console
- 1 node (solution input): http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_solution_input/9/console
> Added IO sanity test error check.

- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/s3-client-setup.sh
- Added support for Release v0.0.18.
-  Added support for Release v0.0.18.
- Single node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/183/console
- 3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/182/console
> EOS-26149: Added support for Release v0.0.18.

- solutions/kubernetes/cortx-deploy-functions.sh
- Added support for Release v0.0.19.
- Added support for Release v0.0.19.
- Single node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/191/console
- 3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/189/console
> EOS-27373: Added support for Release v0.0.19.

- jenkins/automation/kubernetes/prvsnr-framework-deploy.groovy
- Require support for Nightly builds.
-  Added support for Nightly builds.
> EOS-27536: Added support for Nightly builds.

- jenkins/automation/kubernetes/prvsnr-framework-deploy.groovy
- solutions/kubernetes/cluster-functions.sh
- Added update for calico image release.
-  Added update for calico image release.
- Single node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_k8s_setup/70/
- 3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_k8s_setup/69/
> EOS-27373: Added update for calico image release.

- jenkins/automation/kubernetes/prvsnr-framework-deploy.groovy
- Added update for hosts parameter in nightly configuration.
-  Added update for hosts parameter in nightly configuration.
- http://eos-jenkins.colo.seagate.com/job/Provisioner/job/prvsnr_framework_deployment/12/
> EOS-27536: Added update for hosts parameter in nightly configuration.

- .github/workflows/dispatch_submodule_update.yml
RE's submodule is missing in parent repository
Whenever code push in main branch the submodule event is dispatched to add it to parent repository
> EOS-26653: Added the dispatch event

- jenkins/automation/alex.groovy
Pre-built docker images is having conflict in the node packages with Alex packages.
Created the new agent in jenkins
> EOS-25493: Changed the agent for Alex

- jenkins/automation/kubernetes/cortx-all-image.groovy
- jenkins/custom-ci/generic/cortx-ha.groovy
- jenkins/custom-ci/generic/cortx-py-utils.groovy
- jenkins/custom-ci/generic/cortx-rgw.groovy
- jenkins/custom-ci/generic/csm-agent.groovy
- jenkins/custom-ci/generic/custom-ci.groovy
- jenkins/custom-ci/generic/hare.groovy
- jenkins/custom-ci/generic/motr.groovy
- jenkins/custom-ci/generic/provisioner.groovy
> Rocky Linux 8.4 Custom-CI pipelines

- jenkins/internal-ci/centos-7.9.2009/pr/cortx_deployment/csm_agent.groovy
- PR build was still installing cortx-prereq package which is causing the issue. Removed cortx-prereq installation. 
> EOS-28498 All CSM PR build deployments are failing

- jenkins/automation/rpm-validation.groovy
- scripts/release_support/rpm-validator.sh
- RPM Validation pipeline was not getting the Jenkins node due to the wrong configuration. 
- Build URL needs to be updated with K8s change. 
> EOS-28346 - Fix RPM Validation Pipeline execution issue. 

- jenkins/automation/kubernetes/cortx-all-image.groovy
Signed-off-by: nikhilpatil2995 <nikhil.patil@seagate.com>
-EOS-27938 - build granular images
> EOS-27938 - CI job for Granular Images

- jenkins/automation/kubernetes/nightly-build-and-deploy.groovy
- Remove custom-ci from cortx-all image name
Email Notification. (Please note Sanity+Regression was disabled )
> CORTX-28592 - Remove custom-ci from cortx-all image name

- solutions/kubernetes/cluster-functions.sh
- solutions/kubernetes/cortx-deploy-functions.sh
- Added support for CORTX Services Release v0.0.22.
Added support for CORTX Services Release v0.0.22.
Single node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/235/
3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/236/
> CORTX-28486: Added support for CORTX Services Release v0.0.22.

- jenkins/automation/kubernetes/cortx-all-image-tagging.groovy
- jenkins/automation/kubernetes/deploy-cortx-k8-cluster.groovy
- jenkins/automation/kubernetes/prvsnr-framework-deploy.groovy
- jenkins/automation/kubernetes/prvsnr-framework-upgrade.groovy
- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/ova/kubernetes/ova-solution.yaml
- Use ghcr.io/seagate/cortx-all:2.0.0-latest tag as default image name.
3Node http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/sv_space/job/setup-cortx-cluster/138/parameters/
1 Node http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/sv_space/job/setup-cortx-cluster/139/console
> CORTX-28592  Use ghcr.io/seagate/cortx-all:2.0.0-latest tag as default image

- jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy
- EOS-28500- csm-agent groovy script is hardcoded for pyutils build
-  For Bug, parameters are hardcoded in the cms-agent groovy script.
http://eos-jenkins.mero.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/2184/console
> EOS-28500 - csm-agent groovy script is hardcoded for pyutils build

- docker/jenkins/prod_jenkins/docker-compose.yaml
Jenkins not runs on HTTPS
Added the SSL cert to have secured connection in jenkins server
> CORTX-28287: Added SSL cert for jenkins server

- jenkins/automation/kubernetes/deploy-cortx-k8-cluster.groovy
- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- cortx-k8s Jenkins job is running on S3 way of deployment 
-  Shift deployment method to RGW based deployment
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/gc-space/job/setup-k8s-cortx-cluster/6/
> CORTX-29213 : Update k8s-cortx jenkins job for rgw based deployment

- jenkins/internal-ci/generic/branch/cortx-ha.groovy
- jenkins/internal-ci/generic/branch/cortx-images.groovy
- jenkins/internal-ci/generic/branch/cortx-py-utils.groovy
- jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy
- jenkins/internal-ci/generic/branch/cortx-rgw.groovy
- jenkins/internal-ci/generic/branch/csm-agent.groovy
- jenkins/internal-ci/generic/branch/hare.groovy
- jenkins/internal-ci/generic/branch/motr.groovy
- jenkins/internal-ci/generic/branch/provisioner.groovy
- jenkins/internal-ci/generic/branch/release.groovy
- auto-jira comment was not enabled for all components.
- cortx-control image was not part of mail notification.
-  Enabled auto-jira comment for all components
-  Added cortx-control image location in cortx-image mail notification
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/gc-space/job/cortx-image/3/
> CORTX-29215 : Enable auto-Jira comments and print cortx-control image details

- jenkins/automation/changelog-generation.groovy
- scripts/release_support/changelog.sh
- Added support for RGW components in changelogs generation.
> CORTX-29301 - Add support for RGW components in changelog generation.

- solutions/ova/kubernetes/firstboot.service
- solutions/ova/kubernetes/firstboot.sh
- solutions/ova/kubernetes/kubectl_alias.sh
- solutions/ova/kubernetes/ova-solution.yaml
OVA solution.yaml file is not updated
Added the updated solution.yaml file
> CORTX-29295: Updated OVA solution.yaml file for RGW

- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/io-testing.sh
- Services team released new version v0.2.0 for deployment
-  Update deployment to support v0.2.0
1-node - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1358/
3-node - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1357/
> Adhoc : update deployment for services version v0.2.0

- scripts/rgw/ceph/README.md
- scripts/rgw/ceph/ceph.spec.template
- Template file with optional parameters to reduce build time.
-  Added ceph.spec.template file.
> CORTX-27706: Added ceph.spec.template.

- jenkins/internal-ci/generic/branch/release.groovy
- Release Build pipeline failing with below error due to syntax error. Refer - https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/view/Main_Dashboard/job/Release/5227/console . Fixed it as part of this change. 
```
Started by user [Shailesh Vaidya](https://eos-jenkins.colo.seagate.com/user/729494)
Obtained ./jenkins/internal-ci/generic/branch/release.groovy from git https://github.com/Seagate/cortx-re
Running in Durability level: MAX_SURVIVABILITY
[Checks API] No suitable checks publisher found.
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 309: expecting ']', found 'string' @ line 309, column 25.
string(name: 'CORTX_DATA_IMAGE', value: "${env.cortx_data_image}")
^
1 error
at …
```
> CORTX-29649 - Fixed syntax issue in Release Build pipeline

- jenkins/internal-ci/generic/pr/cortx_deployment/csm-agent.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/ha.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/motr.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/provisioner.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
- PR deployment scripts were not updated to support data-only pod deployment
-  Updated PR deployment scripts to support data-only pod deployment
csm-agent - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/csm-agent/133/
ha - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/ha/31/
hare - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/hare/127/
provisioner - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/provisioner/72/
motr - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Gene …
> CORTX-29650 : Data-only pod changes for PR deployments

- solutions/kubernetes/cortx-deploy-functions.sh
- solution.yaml to be removed as part of https://github.com/Seagate/cortx-k8s/pull/191 Modified framework to create solution.yaml before executing prereq script
> CORTX-29649 Create solution.yaml before executing prereq script

- jenkins/automation/alex.groovy
Inconsiderate word found
Removed the problematic word
> CORTX-29224: Removed the inconsiderate word

- scripts/automation/rpm_cleanup.sh
- scripts/mini_provisioner/roles/csm/tasks/01_install_prerequisites.yml
- Alex scan reported `udx` word. This change will remove it from repository.
> CORTX-30540 Alex Scan Report - Remove udx word

- solutions/kubernetes/cluster-setup.sh
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- solutions/kubernetes/functions.sh
-  We have `/dev/sdb` drive hardcoded in scripts. We need to take it as input for community deployment. This change modifies scripts to take SYSTEM_DRIVE as input. 
> CORTX-30166 - Take system drive as input parameter

- jenkins/automation/kubernetes/nightly-prvsn-sanity-deploy.groovy
Signed-off-by: Aayushi Sharma <aayushi.sharma@seagate.com>
There was no sanity for provisioning.
-  We created a sanity pipeline.
> CORTX-29266 Provisioner Sanity Pipeline

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- Added support for K8s Release v0.3.0:  https://github.com/Seagate/cortx-k8s/tree/v0.3.0
> CORTX-30169 Added support for K8s Release v0.3.0

- jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
- Run py-utils every night with tests execution and send mail notification to foundation team.
-  Added py-utils test stage, cron for nightly trigger and mail notification block for nightly result with test report in it.
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/py-utils-test/102/
> CORTX-29518 : Build nightly py-utils

- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
-  Seems solution.yaml input is mandatory for ./prereq-deploy-cortx-cloud.sh now. Update code to provide solution.yaml. 
```
[root@ssc-vm-rhev4-1940 k8_cortx_cloud]# ./prereq-deploy-cortx-cloud.sh -d /dev/sdb
ERROR: solution.yaml does not exist
```
> CORTX-30831 3N k8s deployment jobs are failing

- scripts/release_support/rpm-validator.sh
- RPM validation has s3 rpm which is obsolete now and rgw rpm is not present
-  Removed s3 and added rgw rpm in validation.
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/Cortx-Automation/job/rpm-validation-report/390/
> CORTX-29805 : Update rpm validation

- solutions/kubernetes/cortx-deploy.sh
- Updated default tag for K8s codebase
> CORTX-30946 Update default tag for K8s codebase

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/kubernetes/cortx-deploy-functions.sh
- Conul POD creation is failing with below error 
```
==> failed to parse /consul/config/..2022_04_22_05_03_34.789462202/client.json: 1 error occurred:
* invalid config key auto_reload_config
```
Modified code to pull the latest Consul image `cortx-docker.colo.seagate.com/consul/consul:1.12` to avoid deployment failure. 
> CORTX-30971 Update consul image version to fix deployment issue.

- solutions/kubernetes/cortx-deploy-functions.sh
- Add support for https://github.com/Seagate/cortx-k8s/tree/v0.4.0 in CORTX RE scripts.
> CORTX-30946 Add support for K8s v0.4.0

- docker/cortx-deploy/cortx-control/python_requirements.txt
- docker/cortx-deploy/cortx-data/python_requirements.txt
- docker/cortx-deploy/cortx-rgw/python_requirements.txt
- docker/cortx-deploy/python_requirements.txt
- scripts/third-party-rpm/python_requirements.txt
Package Name  | Cryptography
Version | 3.3.2
license | Apache Software License, BSD License (BSD Or Apache License Version 2.0)
Source  | https://github.com/pyca/cryptography/
**Yes, all the test results are uploaded in a document. This document is attached to https://jts.seagate.com/browse/CORTX-29993**
wheel file is downloaded from https://pypi.org/project/cryptography/3.3.2/#files
cryptography-3.3.2-cp36-abi3-manylinux1_x86_64.whl
https://pypi.org/project/cryptography/3.3.2/#files
Apache / opensource community
No configuration required
cortx-re is responsible for deployment
This is Apache Software License, BSD License (BSD Or Apache License Version 2.0) license. 
This library is upgrade from version 2.8 to 3.3.2
> CORTX-29993 - Update cryptography library

- solutions/ova/kubernetes/ova-solution.yaml
The solution.yaml file is not matched with latest cluster version
Updated the solution.yaml file
> CORTX-30853: Updated the PI-6 solution.yaml file

- solutions/community-deploy/cloud/AWS/tool_setup.sh
- AWS CLI installation was failing due to the absence of unzip command. Added unzip package installation steps. 
> CORTX-30946 Added unzip package installation

- jenkins/automation/rgw/ceph/ceph-build.groovy
- solutions/kubernetes/ceph-binary-build.sh
- solutions/kubernetes/cluster-functions.sh
- solutions/kubernetes/cortx-deploy-functions.sh
- Ceph binary build automation.
-  Ceph binary build automation.
- Ubuntu: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/54/console
- CentOS: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/56/consoleFull
- Rocky Linux: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/55/consoleFull
> CORTX-30901: Ceph binary build automation.

- solutions/kubernetes/functions.sh
- Performace sanity was failing in subsequent iterations due to disk space issues. Added step to clean-up existing buckets from cluster.
> CORTX-30153 Clean-up existing buckets before IO sanity

- .github/workflows/alex_reviewdog.yml
Alex workflow is getting failed
Changed the permission for github workspace
> CORTX-30785: Alex workflow bug fix on PR

- scripts/provisioner/update_solution.sh
- solutions/kubernetes/cortx-deploy-functions.sh
Signed-off-by: Aayushi Sharma <aayushi.sharma@seagate.com>
- Added Secret Keys Passwords
-  Update secret key
> Adhoc : Update secret key in solution.yaml

- docker/cortx-build/Makefile
- Motr packages are not built with libfabric support. Added libfabric installation in Makefile for Motr
> CORTX-31075 Added libfabric installation in Makefile

- jenkins/automation/rgw/ceph/ceph-build-vm.groovy
- solutions/kubernetes/ceph-binary-build.sh
- Ceph build location path fix.
-  Build location path fix.
Container:
- Ubuntu: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/65/console
- CentOS: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/69/console
- Rocky Linux: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/70/console
VM:
Rocky Linux: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-host/3/console
Checklist for …
> CORTX-31165: Build location path fix.

- jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
- regression, io and domain failure status variables were not included in environment variables.
-  Added required variables in environment variables
https://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/Nightly-K8s-Deploy/755/
> CORTX-31155 : update variables for nightly deployment mail

- solutions/kubernetes/cortx-deploy.sh
- Add support for K8s Release 0.5.0
> CORTX-31176 Add support for K8s Release 0.5.0

- solutions/community-deploy/cloud/AWS/README.md
Updated README.md for formatting. The file describes steps to install and deploy cortx on AWS.
Signed-off-by: Swatid <swati.dhotarkar@seagate.com>
(https://jts.seagate.com/browse/CORTX-31001?src=confmacro)
Non Jenkins RE Deployment steps to be modified for community
- [Done] JIRA number/GitHub Issue added to PR
- [ Done] PR is self reviewed
- [ Done] Jira and state/status is updated and JIRA is updated with PR link
- [Done] Check if the description is clear and explained
-----
[View rendered solutions/community-deploy/cloud/AWS/README.md](https://github.com/swatid-seagate/cortx-re/blob/cortx-on-aws/solutions/community-deploy/cloud/AWS/README.md)
> CORTX-31001: Non Jenkins RE Deployment steps modification for community-CORTX on AWS 

- solutions/community-deploy/CORTX-Deployment.md
Signed-off-by: Swatid <swati.dhotarkar@seagate.com>
-Non Jenkins RE Deployment steps to be modified for community-CORTX-Deployment
https://jts.seagate.com/browse/CORTX-31001
- [Done ] JIRA number/GitHub Issue added to PR
- [ Done] Jira and state/status is updated and JIRA is updated with PR link
- [Done ] Check if the description is clear and explained
-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/swatid-seagate/cortx-re/blob/cortx-deployment-update/solutions/community-deploy/CORTX-Deployment.md)
> CORTX-31001: Non Jenkins RE Deployment steps to be modified for community-CORTX-Deployment

- solutions/kubernetes/cortx-deploy-functions.sh
- Increase default resource limits for 3rd party components
> CORTX-31281 Increase default resource limits for 3rd party components

- jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy
- CORTX-30945: 3N VM deployment needed in Hare PR pre-merge
-  I have made required changes for 3N hare deployment job please find below Tested Jenkins job.
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/ap_space/job/prjobs/job/hare/3/console
> CORTX-30945: 3N VM deployment needed in Hare PR pre-merge

- solutions/kubernetes/cortx-deploy-functions.sh
-  CORTX K8s team has added support for the custom namespace in CORTX deployment. Added support for it in manually created solution.yaml based deployment. 
> CORTX-31176 -  Added support for custom namespace in manually created solution.yaml based deployment. 

- solutions/community-deploy/CORTX-Deployment.md
- solutions/community-deploy/cloud/AWS/README.md
- solutions/kubernetes/cortx-deploy-functions.sh
Signed-off-by: Pranav Sahasrabudhe <Pranav.p.Sahasrabudhe@seagate.com>
- Problem statement
-----
[View rendered solutions/community-deploy/cloud/AWS/README.md](https://github.com/pranav-sahasrabudhe/cortx-re/blob/add_tester/solutions/community-deploy/cloud/AWS/README.md)
> CORTX-31294: Updated README.md with "Tested by section"

- jenkins/automation/s3server/s3_ceph_testcase.groovy
- jenkins/automation/s3server/s3_splunk_testcase.groovy
- Configurable RE repo and branch for S3 compliance pipelines
- Use Docker containers to execute S3 compliance pipelines
> CORTX-31176 - Configurate RE repo and branch for S3 compliance pipelines

- docker/cortx-deploy/Dockerfile
- Debug packages are added in cortx images
-  Removed debug package folder from cortx-images 
> CORTX-30765 : Remove debug packages from cortx images

- solutions/community-deploy/Communitybuild.sh
Signed-off-by: Abhirup Ghosh <abhirup.ghosh@seagate.com>
- CORTX-30171 update on community build script
> CORTX-30171 Update on community build script

- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- Add support for https://github.com/Seagate/cortx-k8s/tree/v0.6.0
> CORTX-31410 - Add support for CORTX-K8s Release 0.6.0

- docker/cortx-deploy/compatibility.info
- Added support for downgrade compatibility. 
```
[root@ssc-vm-rhev4-0707 ~]# docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.version"}}' cortx-docker.colo.seagate.com/seagate/cortx-data:2.0.0-6214-custom-ci
CORTX >= 2.0.0-0 <= 2.0.0-0, cortx-motr >= 2.0.0-0 <= 2.0.0-0, cortx-rgw >= 2.0.0-0 <= 2.0.0-0, cortx-hare >= 2.0.0-0 <= 2.0.0-0, cortx-py-utils >= 2.0.0-0 <= 2.0.0-0, cortx-csm_agent >= 2.0.0-0 <= 2.0.0-0, cortx-ha >= 2.0.0-0 <= 2.0.0-0, cortx-prvsnr >= 2.0.0-0 <= 2.0.0-0
[root@ssc-vm-rhev4-0707 ~]#
```
Checklist for …
> CORTX-31074 Add 'REQUIRES' section in cortx docker images for version compatibility check

- solutions/ova/kubernetes/ova-solution.yaml
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- OVA solution.yaml file for v0.6.0 where cortx-all image is removed
> CORTX-31290: OVA Solution spec for v0.6.0

- solutions/community-deploy/build-cortx.sh
- solutions/community-deploy/cloud/AWS/README.md
- solutions/community-deploy/cloud/AWS/single-node.tf
- Increased root volume of EC2 instance to support RGW package creation. 
```
#time ./build-cortx.sh
Docker Image push skipped
cortx-all:2.0.0-0 2022-05-27 08:45:44 +0000 UTC
cortx-rgw:2.0.0-0 2022-05-27 08:41:03 +0000 UTC
cortx-data:2.0.0-0 2022-05-27 08:34:23 +0000 UTC
cortx-control:2.0.0-0 2022-05-27 08:29:29 +0000 UTC
real    207m22.202s
user    0m18.460s
sys     0m15.119s
```
> CORTX-30171 Automate Community build creation on EC2 instance

- solutions/community-deploy/CORTX-Deployment.md
- solutions/kubernetes/cortx-deploy.sh
-  Updated community build steps document. Updated script to set `Nodeport` as the default external service. 
-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/shailesh-vaidya/cortx-re/blob/communiity-build-fix/solutions/community-deploy/CORTX-Deployment.md)
> CORTX-30171 - Updated community build steps document and script.

- jenkins/automation/rgw/ceph/ceph-build-docker.groovy
- jenkins/automation/rgw/ceph/ceph-build-vm.groovy
- solutions/kubernetes/ceph-binary-build.sh
- solutions/kubernetes/ceph-deploy-functions.sh
- solutions/kubernetes/functions.sh
- solutions/kubernetes/io-sanity.sh
- Added error check and upload rpm fix for vm builds.
-  Added error check and upload rpm fix for vm builds.
- vm build with upload rpm: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-host/8/console
- vm build error check: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-host/7/console
- docker build: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/96/console
- ceph-ubuntu-deploy: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-deploy/52/console
Checklist …
> CORTX-30132: Added error check and upload rpm fix for vm builds.

- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- setup-cortx-rgw-cluster failure is not handled
- Added error check for cleanup and pdsh commands.
- Successful deployment: https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/6169/console
- Error check deployment: https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/6173/console
> CORTX-31353: setup-cortx-rgw-cluster failure is not handled

- solutions/ova/kubernetes/ova-solution.yaml
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Minor fix in ova solution file
> CORTX-31290: Update setup_size to large in ova solution file

- solutions/kubernetes/cortx-deploy-functions.sh
- Remove setup_size parameter from solution.yaml 
> CORTX-31968 Remove setup_size parameter from solution.yaml

- jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
- Use cortx-cicd@seagate.com email alias for nightly build notification. This will make email recipient update easy.
> CORTX-31968 Use cortx-cicd@seagate.com email alias for nightly build notification

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- jenkins/custom-ci/generic/custom-ci.groovy
- Increase build retention period for custom-ci and CORTX deployment jobs.
> CORTX-31968 Increase build retention period for custom-ci and CORTX deployment jobs.

- jenkins/automation/alex.groovy
- scripts/automation/alex/alex.py
- scripts/automation/alex/alex_pickle.py
Signed-off-by: subhalaxmisa <subhalaxmi.sahoo@seagate.com>
- Fix Alex monthly report
Fix Alex monthly report
> CORTX-31840 - Fix Alex monthly report

- jenkins/internal-ci/generic/pr/cortx_deployment/csm-agent.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/ha.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/hare.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/motr.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/provisioner.groovy
- jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy
- PR deployment groovy files were in feature branch
-  Adding all files in `main` branch.
CSM - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/csm-agent/390/
Utils - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/py-utils/372/
Provisioner - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/provisioner/211/
Motr - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/motr/863/
Hare - https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deploym …
> CORTX-30156 : Add component pr-deployment groovy files

- jenkins/automation/s3server/s3_ceph_testcase.groovy
- scripts/automation/s3-test/create_account.sh
- scripts/automation/s3-test/run_testcases.sh
- Jenkins Nightly-Regression-Ceph-Splunk-RGW failing.
-  Updated the CSM IAM API url along with other small changes.
- https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/S3Server/job/Nightly-Regression-Ceph-Splunk-RGW/87/console
> CORTX-32011: Jenkins Nightly-Regression-Ceph-Splunk-RGW failing.

- solutions/kubernetes/cluster-functions.sh
- K8s deployment is failing in CNI pod creation. Updated script to use docker-ce-20.10.8
> CORTX-32381 - Use docker-ce-20.10.8 to avoid CNI container creation issue

- README.md
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Fix Codacy Badge
-----
[View rendered README.md](https://github.com/Seagate/cortx-re/blob/mukul-codacybadge/README.md)
> CORTX-31845: Fix Codacy Badge

- solutions/kubernetes/ceph-binary-build.sh
- When user passes ceph/cortx-rgw repo with .git (https://github.com/andriytk/ceph.git) in the CEPH_REPO/CORTX_RGW_URL the build fails because the git command clones the repo in ceph/cortx-rgw dir but since we are dynamically getting ceph/cortx-rgw in REPO_COMPONENT it substitute & sets it value as ceph.git/cortx-rgw.git and script tries to find ceph.git/cortx-rgw.git dir instead of cloned ceph/cortx-rgw dir. 
- Handled ".git" also for ceph/cortx-rgw repos.
- ceph.git-build: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/163/console (build failed because of changes …
> CORTX-32121: ceph-binary-build reponame ".git" fix

- jenkins/env_setup/Jenkinsnodedetails.groovy
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/functions.sh
- Need actual tag of latest tagged image
-  Fetching actual tag from image metadata.
1N - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/8219/
3N - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/8221/
> CORTX-32703 : Fetch original tag from latest image

- jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw.groovy
- solutions/kubernetes/ceph-binary-build.sh
- cortx-rgw PR based deployment is failing
-  Fixed checkout of pr branch.
- PR build (rebuild 19): https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/cortx-rgw/25/consoleFull
- https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/ceph-build-container/179/console
- cortx-rgw main: https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/view/Main_Dashboard/job/cortx-rgw/5207/
> CORTX-32926: cortx-rgw PR based deployment is failing

- jenkins/internal-ci/generic/pr/cortx_deployment/cortx-rgw.groovy
- solutions/kubernetes/ceph-binary-build.sh
- Problem with pr-checkout.
-  Changed pr id checkout method.
- pr build: https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/cortx-rgw/37/console
- cortx-rgw: https://eos-jenkins.colo.seagate.com/job/Cortx-Main/job/rockylinux-8.4/job/cortx-rgw/5209/console
- ceph-build: https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/Ceph/job/ceph-build-container/50/console
> CORTX-32926: pr id checkout change.

- jenkins/automation/kubernetes/destroy-cluster.groovy
- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- jenkins/automation/kubernetes/setup-k8-cluster.groovy
- jenkins/custom-ci/generic/custom-ci.groovy
- jenkins/internal-ci/centos-7.8.2003/main/cortx-ha.groovy
- jenkins/internal-ci/generic/branch/cortx-ha.groovy
- jenkins/internal-ci/generic/branch/cortx-images.groovy
- jenkins/internal-ci/generic/branch/cortx-py-utils.groovy
- jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy
- jenkins/internal-ci/generic/branch/cortx-rgw.groovy
- jenkins/internal-ci/generic/branch/csm-agent.groovy
- jenkins/internal-ci/generic/branch/hare.groovy
- jenkins/internal-ci/generic/branch/motr.groovy
- jenkins/internal-ci/generic/branch/provisioner.groovy
- jenkins/internal-ci/generic/branch/release.groovy
- Remove hardcoded email address from Jenkins job configuration 
> CORTX-33187 Remove hardcoded email address from Jenkins job configuration

- jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
Signed-off-by: akshaym99 <akshay.s.mankar@seagate.com>
- CICD: Update stage duration & test count in email report.
-  Jira task: https://jts.seagate.com/browse/CORTX-32224
> CORTX-32224 stage duration & test count

- jenkins/deployment/community/cortx-community-deploy.groovy
Signed-off-by: Abhirup Ghosh <abhirup.ghosh@seagate.com>
- Job was getting aborted if the total build time exceed 4 hours and in post build action [ Destroy EC2] was failing from some internal error without retrying again. Refer: https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/Community/job/Community-deploy/12/
-  For Bug: Added the retry option in post build action for destroying the EC2 instance properly.
-  For Feature: Increased the timeout of the script to 6 hours 
> CORTX-32739: Automated EC2 build and deploy pipeline is getting aborted.

- jenkins/automation/kubernetes/cortx-all-image-tagging.groovy
- jenkins/internal-ci/generic/branch/release.groovy
- Add 1N and 3N deployment check for Release
> CORTX-33188 Add 1N and 3N deployment check for Release

- jenkins/internal-ci/generic/branch/cortx-rgw-integration.groovy
- jenkins/internal-ci/generic/branch/hare.groovy
- jenkins/internal-ci/generic/branch/motr.groovy
- Email notification is not sent to developers. Enabled this in Jenkinsfile.
> Ad Hoc Request: Enable email notification to component developers

- jenkins/automation/kubernetes/setup-cortx-cluster.groovy
- solutions/kubernetes/io-sanity.sh
- Support bundle generation is failing in setup-cortx-rgw-cluster pipeline
1. File type for support bundle was changed from tar to tgz.
Failed job: https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_rgw_cluster/53/console
> CORTX-33629: Support bundle generation is failing in setup-cortx-rgw-cluster pipeline

- jenkins/automation/changelog-generation.groovy
- scripts/release_support/changelog.sh
- Changelog has many information fields
-  Remove needless fields and update changelog for community purpose
> CORTX-32961 : Update changelog generation

- jenkins/internal-ci/centos-7.8.2003/cortx-1.0/release
- jenkins/internal-ci/centos-7.8.2003/main/release.groovy
- jenkins/internal-ci/centos-7.8.2003/stable/release.groovy
- jenkins/internal-ci/centos-7.9.2009/branch/release.groovy
- jenkins/internal-ci/generic/branch/release.groovy
- jenkins/opensource-ci/ova-build/ova-release.groovy
- scripts/release_support/ova-release-notes/ova_release.py
- Release failing due to changelog file extension got changed to `.md` from `.txt`
-  Fix file extension for changelog
> CORTX-32961 : Update changelog file extension

- jenkins/internal-ci/generic/branch/release.groovy
- jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
- jenkins/internal-ci/generic/nightly/nightly-upgrade.groovy
- jenkins/opensource-ci/ova-build/ova-release.groovy
- scripts/release_support/changelog.sh
- Release has `.txt` extension for changelog which is now changed to `.md`
-  Change file extension to `.md`
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/gc-space/job/changelog-test/25/
> CORTX-32961 : Update changelog file extension and info message

- jenkins/deployment/community/cortx-community-deploy.groovy
- solutions/community-deploy/cloud/AWS/main.tf
- solutions/community-deploy/cloud/AWS/user.tfvars
- solutions/community-deploy/cloud/AWS/variable.tf
- Modification to Configurable AWS EBS volumes.
1. Modify ebs volumes count & size.
1. Job: 
> CORTX-33719: Modification to Configurable AWS EBS volumes.

- scripts/reports/repo-health.sh
Signed-off-by: subhalaxmisa <subhalaxmi.sahoo@seagate.com>
- Automate Alex data in health report
-  Automate Alex data in health report
> CORTX-33581 : Automate Alex data in health report

- jenkins/internal-ci/generic/pr/component_test/Motr_Pre_merge_DTM_Integration.groovy
- Remove ghprbGhRepository and ghprbAuthorRepoGitUrl print debug statements. Job breaks if triggered manually due to this. 
> CORTX-33695 Remove ghprbGhRepository and ghprbAuthorRepoGitUrl print debug statements

- jenkins/automation/alex.groovy
Signed-off-by: subhalaxmisa <subhalaxmi.sahoo@seagate.com>
- Include cortx-cc repo in Alex scan report
-  Include cortx-cc repo in Alex scan report
> CORTX-33614 : Include cortx-cc repo in Alex scan report

- jenkins/automation/splint-memory-leak.groovy
- Created Jenkins pipeline to integrate SpLint tool to detect Memory leaks Motr Repo. Jenkins pipeline will take Motr Repo details (Repo URL and Branch) as input and generate a report. The report URL will be sent to the developer as an email notification. 
> CORTX-33862 Integrate SpLint tool to detect Memory leaks Motr Repo

- solutions/community-deploy/CORTX-Deployment.md
Signed-off-by: Mukul Malhotra <mukul.malhotra@seagate.com>
- Changes added to update CORTX-Deployment.md with command to override & avoid the parameter to pull the images from GHCR
-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/Seagate/cortx-re/blob/mukul-multinode-deployment/solutions/community-deploy/CORTX-Deployment.md)
> CORTX-32909: Update minor CORTX-Deployment.md Instructions with locally generated images support

- scripts/performance/cortx-perfline.sh
- solutions/community-deploy/CORTX-Deployment.md
- solutions/kubernetes/cortx-deploy.sh
- Add support for K8s Services v0.10.0
> CORTX-33942 - Add support for K8s Services v0.10.0 

- solutions/kubernetes/io-sanity.sh
Signed-off-by: Kapil Jinna <kapil.jinna@seagate.com>
Remove multipart tests from sanity
> CORTX-33975 remove multipart tests from sanity

- solutions/kubernetes/io-sanity.sh
Signed-off-by: Kapil Jinna <kapil.jinna@seagate.com>
Enable multipart tests in deployment sanity.
> CORTX-33975 Enable multipart tests in sanity

- jenkins/custom-ci/generic/cortx-rgw.groovy
- jenkins/custom-ci/generic/custom-ci.groovy
- jenkins/custom-ci/generic/motr.groovy
- solutions/kubernetes/ceph-binary-build.sh
- `xmlstarlet ` package is not available through EPEL repo for cortx-rgw repo. Added package in local repo. 
> CORTX-34078: Install xmlstarlet for cortx-rgw build process

- solutions/kubernetes/cortx-deploy-functions.sh
- Observed hax and confd cpu utilization from long run
testing and reducing the resource requirement of
the containers.
Signed-off-by: Vinoth.V <vinoth.v@seagate.com>
CPU limits is crossing 8  core range in Vms
Reduced cpu limits of hax and confd containers
so the CPU limit will be within 8 core values for VMs.
> CORTX-29967: Updated resource limits to keep with in vm limits.

- jenkins/automation/alex.groovy
- jenkins/automation/kubernetes/nightly-cortx-image.groovy
- jenkins/deployment/vm_deployment/cortx_stack/cortx_deploy_vm_3n.groovy
- jenkins/internal-ci/centos-7.8.2003/main/cortx-ha.groovy
- jenkins/internal-ci/centos-7.8.2003/main/csm-agent.groovy
- jenkins/internal-ci/centos-7.8.2003/main/csm-web.groovy
- jenkins/internal-ci/centos-7.8.2003/main/hare.groovy
- jenkins/internal-ci/centos-7.8.2003/main/motr.groovy
- jenkins/internal-ci/centos-7.8.2003/main/provisioner.groovy
- jenkins/internal-ci/centos-7.8.2003/main/release.groovy
- jenkins/internal-ci/centos-7.8.2003/main/s3server.groovy
- jenkins/internal-ci/centos-7.8.2003/main/sspl.groovy
- jenkins/internal-ci/centos-7.8.2003/stable/csm-agent
- jenkins/internal-ci/centos-7.8.2003/stable/csm-web
- jenkins/internal-ci/centos-7.8.2003/stable/hare
- jenkins/internal-ci/centos-7.8.2003/stable/motr
- jenkins/internal-ci/centos-7.8.2003/stable/nfs
- jenkins/internal-ci/centos-7.8.2003/stable/provisioner
- jenkins/internal-ci/centos-7.8.2003/stable/s3server
- jenkins/internal-ci/centos-7.8.2003/stable/sspl
- jenkins/internal-ci/centos-7.9.2009/pr/mini_provisioning/pyutils-mini_provisioning.groovy
Signed-off-by: pankajgborole <pankaj.g.borole@seagate.com>
Codacy scan has reported code issues for codacy repo 
Codacy issues are reported based on syntax, fixed by using the suggestion provided by Codacy
> CORTX-34087: fix for codacy issues

- scripts/performance/cortx-perfline.sh
- solutions/community-deploy/CORTX-Deployment.md
- solutions/kubernetes/cortx-deploy.sh
- K8s repository version changed to v0.12.0
-  Added support for cortx-k8s v0.12.0 in RE repo
-----
[View rendered solutions/community-deploy/CORTX-Deployment.md](https://github.com/gauravchaudhari02/cortx-re/blob/v0.12.0/solutions/community-deploy/CORTX-Deployment.md)
> CORTX-34145: Update cortx-k8s version to v0.12.0

- solutions/community-deploy/cloud/AWS/README.md
- CORTX-34203: Community build documentation patch to fix the variables
-----
[View rendered solutions/community-deploy/cloud/AWS/README.md](https://github.com/mukul-seagate11/cortx-re-1/blob/mukul-communitybuild-doc-patch/solutions/community-deploy/cloud/AWS/README.md)
> CORTX-34203: Community build documentation patch

- solutions/community-deploy/CORTX-Deployment.md
- solutions/kubernetes/cortx-deploy-functions.sh
- solutions/kubernetes/cortx-deploy.sh
- Services Team has added functionality to provide a custom SSL certificate for CORTX deployment. Steps are documented at https://github.com/seagate/cortx-k8s/tree/v0.12.0#deploy-with-ssl-certificate 
- This PR is to add support for CORTX deployment with a custom SSL certificate in DevOps Scripts. 
- Steps followed to create SSL certificate are as below - 
```bash
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
cat cert.pem key.pem >> custom.pem
```
`CORTX-<5 digit JIRA ID>: <PR Title>` - for …
> CORTX-33010: SSL Certificate Parameterization with CORTX Deployment Jobs

- solutions/dashboard/config/codacy/CodacyCronjob.yaml
- solutions/dashboard/tools/codacy/main.py
- solutions/dashboard/tools/codacy/mongodb.py
Signed-off-by: Sanket Salunke <sanket.s.salunke@seagate.com>
- Cronjob added for codacy
- MongoDB collection initialization logic modified in codacy script
> CORTX-34324: Codacy script modified and Cronjob added

- solutions/dashboard/build/build.sh
- solutions/dashboard/build/dashboard-images.groovy
- solutions/dashboard/build/docker-compose.yml
- solutions/dashboard/deployment/dashboard/codacy.yaml
- solutions/dashboard/deployment/dashboard/portscanner.yaml
- Added Support for Dashboard application container image generation. 
- Added `build.sh` and `docker-compose.yml` to support `codacy` and `portscanner` service container images.
- Added Jenkinsfile and created https://eos-jenkins.colo.seagate.com/job/Dashboard/job/build-dashboard-images/ to generate images.
-----
[View rendered solutions/dashboard/ElasticsearchKibanaInstallation.md](https://github. …
> CORTX-34324: Add Support for Dashboard application container image generation

- scripts/release_support/set-local-repo.sh
- solutions/cortx-motr-apps/jenkins/deploy-motr-apps.groovy
- solutions/cortx-motr-apps/scripts/deploy-motr-apps.sh
- Added Script and Jenkins groovy for setting up the CORTX Motr Apps deployment pipeline. Jenkins pipeline will perform following 
- Set up yum repository for CORTX datapath packages installation from provided GitHub Release details. 
- Create disks, Update CDF configuration file, and setup Cluster.
- Deploy Motr Apps and execute test cases
> CORTX-34348: Add cortx-motr-apps in build

- solutions/dashboard/config/codacy/CodacyDeployment.yaml
- solutions/dashboard/config/logstash/LogstashConfigmap.yaml
- solutions/dashboard/tools/codacy/issues.py
- solutions/dashboard/tools/codacy/main.py
- solutions/dashboard/tools/codacy/repositories.py
- Modified codacy script to display more repository data and levels of issues
- Modified logstash configmap and removed some unused inputs and filters
- Modified CodacyDeployment to replace the image name
> CORTX-34324: Modified Codacy script and Logstash ConfigMap

- solutions/dashboard/deployment/dashboard/dashboardconfigmap.yaml
- solutions/dashboard/deployment/dashboard/logstash.yaml
Signed-off-by: Sanket Salunke <sanket.s.salunke@seagate.com>
- Dashboard deployment YAML files modified
> CORTX-34351: Modified YAML files of dashboard deployment

- .whitesource
- whitesource.config
There is request from PSO team to modify few parameters on Mend side to enable policy checks and license violations
In .whitesource file we need to set enableLicenseViolations=true
If file whitesource.config exists then we need to update checkPolicies=true if not exists then we need to create file with this parameter
CORTX-34384
- [] Jenkins pipelines used for testing
> CORTX-34384: Change to test Whitesource config parameters

- jenkins/automation/vra_infra_provisioner.groovy
- Execute the VMWare provisioner job on the docker swarm node. 
- Added email notification
> CORTX-34400: Execute VMWare provisioner job on docker swarm node.

- solutions/vmware/migration/ansible/vm-metadata-operations/README.md
- solutions/vmware/migration/ansible/vm-metadata-operations/ansible.cfg
- solutions/vmware/migration/ansible/vm-metadata-operations/get_packages.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/install_packages.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/inventories/dev/hosts
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/get_metadata/tasks/main.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/install_packages/files/daemon.json
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/install_packages/handlers/main.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/install_packages/tasks/install_docker.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/install_packages/tasks/install_packages.yml
- solutions/vmware/migration/ansible/vm-metadata-operations/roles/install_packages/tasks/main.yml
- Migration from Cloudform VM's to VMware VM's requires exact package installation from Cloudform to VMware environment VM's.
-  Written a ansible script which gathers packages from Cloudform VM's and installs it on VMware VM's
> CORTX-34395: Ansible script for fetching and installing packages

- jenkins/internal-ci/generic/branch/motr.groovy
- Modified build steps for Motr Ubuntu based build
> CORTX-34414: Fix issue with Motr Ubuntu based build

- solutions/kubernetes/helm/chartrepo/nginx-repo/Readme.md
- solutions/kubernetes/helm/chartrepo/nginx-repo/default.conf
- solutions/kubernetes/helm/chartrepo/nginx-repo/docker-compose.yaml
- Create helm repository using NGINX
- Use docker-compose for implementation
> CORTX-34427: NGINX Helm Repository

- solutions/kubernetes/helm/chartrepo/nginx-repo/Readme.md
- Modify NGINX Helm Repo readme.md
> CORTX-34426: Modify Readme.md of NGINX Helm Repo 
