solutions/kubernetes/cortx-deploy.sh

Signed-off-by: AbhijitPatil1992 <abhijit.patil@seagate.com>
- EOS-26146: Changes for SNS DIX config removed exit1
-  Removed exit 1 from cortx deployment script for SNS and DIX CONFIG.
Here is the jenkins job where I have tested this change.
http://eos-jenkins.colo.seagate.com/job/Cortx-kubernetes/job/setup-cortx-cluster-solution-input/168/console

EOS-26146: Changes for SNS DIX config removed exit1

---

jenkins/automation/kubernetes/k8-custom-ci.groovy
jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy
jenkins/custom-ci/centos-7.9.2009/provisioner.groovy
jenkins/internal-ci/centos-7.9.2009/branch/provisioner.groovy

- Remove obsolete Provisioner RPM's from Kubernetes build generation. This reduces build time and disk usage. 
Tested using 
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/nightly-k8-custom-ci/547/console
http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1471/

EOS-27033 Remove obsolete Provisioner RPM's from kubernetes build generation

---

solutions/kubernetes/cortx-deploy-functions.sh

- Add 60s delay before checking hctl status. 

EOS-26146 Add 60s delay before checking hctl status

---

solutions/kubernetes/cortx-deploy.sh

- On single node deployment, the setup_master function was executing two times.
-  Implemented fix for twice setup_master function execution for single node deployment.
-  Implemented total node count echo flag for multi-node deployment.
- Single node-:
http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/103/parameters/
- 3 node with control node untainted-:
http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_setup/102/parameters/
- 1 + 3 node with control node tainted-:
http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_cortx_set …

EOS-26148: Single node setup_master twice implementation fix.

---

docker/cortx-deploy/python_requirements.txt
docker/cortx-deploy/third-party-rpms.txt
scripts/third-party-rpm/python_requirements.txt

Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
Package Name  | PyYAML
Version | 5.4.1
license | MIT
Source  | https://github.com/yaml/pyyaml
PyYAML library that is current used is version 5.1.2
It needs to be upgraded to 5.4.1
https://github.com/yaml/pyyaml
Yes, detailed testing is conducted and attached as a document to JIRA Bug -> https://jts.seagate.com/browse/EOS-23696
https://pypi.org/project/PyYAML/5.4.1/#files
Its opensource python package.
No configuration required
Provisioner and services team
MIT license, it was the same license as used by PyYAML 5.1.2

EOS-23696 - Upgrade PyYAML package to 5.4.1

---

jenkins/automation/kubernetes/nightly-build-and-deploy.groovy

- We are generating nightly images and storing them in GitHub. This sometimes causes faulty images (deployment not working) stored in GitHub. This PR change will promote cortx-all image from local repo after deployment validation instead in nightly image generation

EOS-26146 - Promote cortx-all image from local repo after deployment validation instead in nightly image generation.

---

docker/cortx-deploy/build.sh
jenkins/automation/kubernetes/cortx-all-image.groovy

- Use internal OS and EPEL repositries for building cortx-all image.

EOS-26146 - Add support to use internal OS repositories.

---

docker/cortx-deploy/build.sh

- Modified get_tag function to use the new provisioner package name. without this change version is not displayed properly.
without change
```
[root@ssc-vm-rhev4-0707 cortx-deploy]# docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.revision"}}' ghcr.io/seagate/cortx-all:2.0.0-latest-custom-ci
cortx-py-utils:3f45b5c, cortx-s3server:4022a4dc, cortx-motr:ae659ec1 ae659ec1, cortx-hare:da6be5a, cortx-csm_agent:308527f2, cortx-prvsnr:,
[root@ssc-vm-rhev4-0707 cortx-deploy]#
```
After change
```
[root@ssc-vm-rhev4-0707 cortx-deploy]# docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.revision"}}' cortx-all:2.0.0-90-kubernetes
cortx-py-utils:3f45b5c, cortx-s3server:4022a4dc, cortx-motr:ae659ec1, cortx-hare:da6be5a, cortx-provisioner:a851e7b5, …
```

EOS-26146 Modify get_tag function to use new provisioner package name

---

jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy
jenkins/custom-ci/centos-7.9.2009/motr.groovy

Signed-off-by: nikhilpatil2995 <nikhil.patil@seagate.com>
- EOS-27074 - Given a choice to user to build motr rpm using kernel mode or user mode

EOS-27074 - Given a choice to user to build motr rpm using kernel mode or user mode (main branch)

---

docker/cortx-build/Makefile

Checkout kubernetes branch failed. Since, there is no kubernetes branch in cortx-k8s repository.
Exclude the kubernetes branch in the checkout list

EOS-26653: Exclude the cortx-k8s in checkout list

---

jenkins/automation/kubernetes/setup-cortx-cluster.groovy
solutions/kubernetes/cortx-deploy.sh

- Use separate stage for IO Test. Sometimes IO test takes more time than expected. Hence created a separate stage for it. This will also enable us to run the IO tests on the already deployed cluster. 

EOS-26147 - Use separate stage for IO Test

---

jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy
jenkins/custom-ci/centos-7.9.2009/custom-ci.groovy
jenkins/internal-ci/centos-7.9.2009/branch/csm-agent.groovy

- csm-agent build process installs cortx-prereq package installation. This installs non-required packages and also increases the build time. This change is to remove cortx-prereq package installation from the csm-agent build process.
custom-ci  - http://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/centos-7.9/job/cortx-all-image-custom-ci/1698/parameters/ 
Tested 3N deployment with image generated from above job i.e. cortx-docker.colo.seagate.com/seagate/cortx-all:2.0.0-1698-custom-ci 
Post-merge check - http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/sv_space/job/s …

EOS-27120 Remove cortx-prereq package installation from csm-agent build process.

---

jenkins/automation/kubernetes/deploy-cortx-k8-cluster.groovy
jenkins/automation/kubernetes/setup-cortx-cluster.groovy

- Add IO sanity test and collect CORTX support bundle on failure.
-  Added IO sanity test and collect CORTX support bundle on failure.
- IO Testing (3 node): http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_deploy_k8s_cortx_cluster/44/console
- CORTX support bundle (3 node): http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_deploy_k8s_cortx_cluster/45/console
- IO Testing (single node): http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_deploy_k8s_cortx_cluster/43/console
Checklist for …

EOS-26654 Added IO sanity test and collect CORTX support bundle on failure.

---

docker/cortx-deploy/Dockerfile
jenkins/internal-ci/centos-7.9.2009/branch/release.groovy

- Add Motr, S3 and Hare debuginfo packages in cortx-all image.
Tested by manually generating image. 
```
[root@ssc-vm-rhev4-0707 cortx-deploy]# docker run --rm cortx-all:2.0.0-748 ls -l /opt/seagate/cortx/debug-packages/
total 23636
-rw-r--r-- 1 root root 14239168 Jan  4 09:59 cortx-motr-debuginfo-2.0.0-302_gitba397044_any.el7.x86_64.rpm
-rw-r--r-- 1 root root  9958632 Jan  4 09:59 cortx-s3server-debuginfo-2.0.0-307_gitc68a968c_el7.x86_64.rpm
```

EOS-25719  Add Motr, S3 and Hare debuginfo packages in cortx-all image.

---

jenkins/custom-ci/centos-7.9.2009/csm-agent.groovy

- Custom build is failing in csm-agent build for forked cortx-utils repo. The build was failing in installing the required python packages due to the hardcoded `Seagate` repo name. Modified logic to use provided cortx-utils forked repo 

EOS-27281 - Custom build is failing in csm-agent build

---

solutions/kubernetes/cortx-deploy.sh

-  setup-cortx-cluster-solution-input Jenkins pipeline is failing with below error - 
```
00:08:33.286 + ./cortx-deploy.sh --io-test
00:08:33.312  is not present
00:08:33.389 Build step 'Execute shell' marked build as failure
00:08:35.232 Archiving artifacts
```

EOS-26147 Fix solution-input pipeline failure

---

jenkins/automation/kubernetes/nightly-build-and-deploy.groovy

-  Remove separate clean-up job. setup-cortx-cluster will ensure cleanup also.  
-  Print RPM build URL used to build the image. As the nightly latest build is used for image creation hence the number in the image name will not match with the build URL. Hence printing the build URL will help to locate rpms. 

EOS-26147 - Remove separate clean-up job, Print RPM build url location

---

scripts/release_support/git-tag.sh

- Problem statement
-  Tagging working fine not we have change some command in git-tag shell script. Please find below shell script and jenkins job links.
https://github.com/AbhijitPatil1992/cortx-re/blob/EOS-27483/scripts/release_support/git-tag.sh
http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/ap_space/job/tagging/18/console

EOS-27483 : Tagging job not working

---

jenkins/internal-ci/centos-7.9.2009/branch/csm-agent.groovy

- csm-agent rpm packages were not getting updated in cortx-all image due to unnecessary when conditionals. 

EOS-27377 - csm-agent rpm packages are not getting updated in cortx-all image

---

solutions/kubernetes/cluster-functions.sh
solutions/kubernetes/cluster-setup.sh
solutions/kubernetes/cortx-deploy-functions.sh
solutions/kubernetes/cortx-deploy.sh
solutions/kubernetes/prvsnr-framework-functions.sh
solutions/kubernetes/prvsnr-framework.sh

- By default during CORTX deployment on fresh VMs busybox image is being downloaded from docker hub even though passing the ghcr.io repo, which runs into errors due to rate limit thus halting deployement.
-  Added fix for busybox. local-path-provisioner is now deployed with CORTX deployment only.
- Fresh VMs single node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_deploy_k8s_cortx_cluster/60/
- Fresh VMs 3 node: http://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/nitisdev/job/test_deploy_k8s_cortx_cluster/61/
After master change
- …

EOS-27573: Added fix for busybox and changed master to primary.

---

solutions/kubernetes/cortx-deploy-functions.sh

-  `docker system prune -a -f` is cleaning up calico plugin images from cluster.   calico-node pods goes to `ImagePullBackOff` state. 
```
[root@ssc-vm-rhev4-1831 ~]# kubectl get pods -A
NAMESPACE            NAME                                                         READY   STATUS                  RESTARTS   AGE
default              consul-client-7lfr7                                          1/1     Running                 0          5m52s
default              consul-client-gtnq7                                          1/1     Running                 0          5m52s
default              consul-client-rmvd8                                          1/1     Running                 0          5m52s
default              consul-server-0                                              1/1 …
```

CORTX-28592 - Exclude calico plugin images from prune

---

docker/cortx-deploy/python_requirements.ext.txt
scripts/third-party-rpm/python_requirements.ext.txt

Package Name  | numpy
Version | 1.19.5
license | BSD
Source  | https://pypi.org/project/numpy/1.19.5/
Minor upgrade from 1.19.2 to 1.19.5 (for compliance)
https://github.com/numpy/numpy
whl file is picked up from https://pypi.org/project/numpy/1.19.5/ - 
numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
https://pypi.org/project/numpy/1.19.5/#files
opensource community
No configuration required.
cortx-re
This is minor version upgrade
version 1.19.2 is in use for long time.
As per whitesource tool, it has BSD license.
Legal team hasn't reported any non compliance

CORTX-28927 - upgrade package numpy from 1.19.XX to 1.19.5

---

jenkins/internal-ci/centos-7.9.2009/branch/csm-agent.groovy

-  csm-agent Jenkins pipeline was failing as it's installing cortx-py-utils from the old location. Modified code to install it from the branch and os provided to Jenkins pipeline.  e.g.  https://eos-jenkins.colo.seagate.com/job/Cortx-Kubernetes/job/post-merge/view/Main_Dashboard/job/csm-agent/319/

CORTX-28911 - Set yum repo for cortx-py-utils packages based on branch and os variable. 

---

jenkins/internal-ci/generic/nightly/nightly-deploy.groovy
solutions/kubernetes/io-testing.sh

- Deployment is failing in few cases if default AWS region is not set. Added command to set default aws region.

CORTX-29301 Set default AWS region for IO Testing

---

docker/cortx-deploy/cortx-control/third-party-rpms.txt
docker/cortx-deploy/cortx-data/third-party-rpms.txt
docker/cortx-deploy/cortx-rgw/third-party-rpms.txt
docker/cortx-deploy/rockylinux-8.4/third-party-rpms.txt

Consul version update to 1.11.4 is required for getting some fixes from
hashicorp project, which are required to resolve some issues seen in
cortx project - one such issue is - CORTX-28823.
Jq version update is required for the issue seen - CORTX-29150
Package Name  |  consul 
Version | 1.11.4
license | hashicorp consul
Source  | https://www.consul.io/downloads
Package Name  | jq
Version | 1.6-3
license |
Source  | http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/jq-1.6-3.el8.x86_64.rpm
To resolve some issues seen in cortx project - one such issue is - CORTX-28823.
consul:- https://www.consul.io/downloads
jq:- http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/jq-1.6-3.el8.x86_64.rpm …

CORTX-29309:Update consul and jq software version 

---

solutions/kubernetes/cortx-deploy-functions.sh

- Need to update [RE](https://github.com/Seagate/cortx-re) codebase for changes from services version [v0.2.1](https://github.com/Seagate/cortx-k8s/releases/tag/v0.2.1)
-  Updated [RE](https://github.com/Seagate/cortx-re) codebase to support services version [v0.2.1](https://github.com/Seagate/cortx-k8s/releases/tag/v0.2.1)
https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1613/

CORTX-29650 : update deployment to support v0.2.1

---

solutions/kubernetes/cortx-deploy-functions.sh

- prereq-deploy-cortx-cloud.sh is failing due to incorrect parameters  Error shown are as below. Refer https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/1709/console
```
19:18:06  ssc-vm-rhev4-1838: ERROR: Invalid input parameters
19:18:06  ssc-vm-rhev4-1838: 
19:18:06  ssc-vm-rhev4-1838: Usage:
19:18:06  ssc-vm-rhev4-1838:     prereq-deploy-cortx-cloud.sh -d DISK [-s SOLUTION_CONFIG_FILE] [-p] [[-b] [-c SEPARATOR]]
19:18:06  ssc-vm-rhev4-1838:     prereq-deploy-cortx-cloud.sh -h
19:18:06  ssc-vm-rhev4-1838: 
19:18:06  ssc-vm-rhev4-1838: Options:
19:18:06  ssc-vm-rhev4-1838:     -h              Prints this help information.
19:18:06  ssc-vm-rhev4-1838: 
19:18:06  ssc-vm-rhev4-1838:     -d <DISK>       REQUIRED. The path of the disk or device to …
```

CORTX-29649 Update parameter for prereq-deploy-cortx-cloud.sh

---

docker/cortx-build/Dockerfile
docker/cortx-build/Makefile
docker/cortx-build/docker-compose.yml
jenkins/automation/docker-image-ci.groovy

-  install-deps script was failing for cortx-rgw build with ` Module yaml error: Unexpected key in data: static_context [line 9 col 3]` error.  Installed `libmodulemd` package in cortx-build image to avoid this error. 

CORTX-30701 Community Build-2.0.0-670: Deployment issue

---

docker/cortx-build/Makefile

-  CORTX RGW build steps is failing for community-build instructions from https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md 
Error reported is 
```
Complete!
make-dist: Full path to the script: /cortx-workspace/cortx-rgw/make-dist
make-dist: No .git present. Run this from the base dir of the git checkout.
ERROR: cortx-rgw source code is not available in cortx-workspace. Exiting...
make: *** [Makefile:181: _cortx-rgw_prereq] Error 1
```
We have added [cortx-rgw](https://github.com/Seagate/cortx-rgw) as a submodule to [cortx](https://github.com/Seagate/cortx/) repo as part of https://github.com/Seagate/cortx/pull/1387. cortx-rgw itself has a submodule structure that is not working in `make-dist` execution. To fix this added code to clone cortx-rgw …

CORTX-30701 Community build cortx-rgw build is failing

---

solutions/kubernetes/cluster-functions.sh

-  We are using the latest Calico v3.22.2. It's causing the issue in the Calico pod setup with the below error,
```
[root@ssc-vm-g4-rhev4-1296 ~]# kubectl -n kube-system  logs calico-node-pks22
2022-04-21 11:18:28.951 [INFO][9] startup/startup.go 425: Early log level set to info
2022-04-21 11:18:28.952 [INFO][9] startup/utils.go 127: Using NODENAME environment for node name ssc-vm-g4-rhev4-1296.colo.seagate.com
2022-04-21 11:18:28.952 [INFO][9] startup/utils.go 139: Determined node name: ssc-vm-g4-rhev4-1296.colo.seagate.com
2022-04-21 11:18:28.952 [INFO][9] startup/startup.go 94: Starting node ssc-vm-g4-rhev4-1296.colo.seagate.com with version v3.22.2
2022-04-21 11:18:28.954 [INFO][9] startup/startup.go 430: Checking datastore connection
2022-04-21 11:18:28.970 [INFO][9] …
```

CORTX-30961 Use Calico v3.20.1 to fix current K8s setup failure

---

jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy

- All test plans were not added in py-utils pre-merge job
- Added remaining test plans in py-utils pre-merge job
https://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/Cortx-Deployment/job/Generic/job/py-utils-test/114/

CORTX-29518 : Add test plans in py-utils pre-merge job

---

jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- Nightly Job continues to upload images to GitHub even if deployment is failing. Refer - https://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/Nightly-K8s-Deploy/747/console  . Removed Try-Catch block which is causing issue. 

CORTX-30946 Nightly Job to exclude further stages in case of deployment failure

---

jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- Nightly deployment mail notification headline status is different than internal QA status
-  Add variable with actual test result values instead of hardcoded status values.

CORTX-31155 : Update nightly mail message

---

jenkins/custom-ci/generic/cortx-ha.groovy
jenkins/custom-ci/generic/cortx-py-utils.groovy
jenkins/custom-ci/generic/csm-agent.groovy
jenkins/custom-ci/generic/custom-ci.groovy
jenkins/custom-ci/generic/provisioner.groovy

- csm, ha, provisioner rpms get built everytime and increase total build time.
-  Provide option to freshly build csm, ha, provisioner rpm or else take it from last successful build.
custom-ci - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/custom-ci-test/223/
Deployment using images generated by above custom-ci - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/4377/

CORTX-31080 : Add option to skip fresh builds for management components

---

docker/cortx-build/Makefile

- Community Build was failing in the installation of `castxml` package. This is an issue due to dependency management in the EPEL repo. Raised https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2087619 for this. To fix this issue added the required packages in https://github.com/Seagate/cortx/releases/tag/build-dependencies 

CORTX-31398 Community Build is failing while Motr dependency installation.

---

jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- Multiple regression status inputs are coming from QA job and hence it is difficult to provide overall regression status
-  Take overall regression status from QA job and provide it to email template

CORTX-31410 : Add overall regression status in nightly deployment

---

jenkins/automation/kubernetes/setup-cortx-cluster.groovy

- Observed that CORTX deployment is failing with timeout with `Loadbalancer` service. Configured `nodeport` as default service in Jenkins pipeline. 

CORTX-31634 Use nodeport as default service in Jenkins pipeline

---

jenkins/automation/reports/repo-health.groovy
scripts/reports/repo-health.sh

- Repo health pipeline was hardcoded to use `main` branch and `https://github.com/Seagate/cortx` repo url. Modified it to take it as a parameter. 

CORTX-31968 - Parametrized repo_health build

---

docker/cortx-deploy/third-party-rpms.txt

Remove python3-ldap package from cortx-rgw image
Package Name  |  python3-ldap
Version | 3.3.1-2.el8
license |
Source  | 
Component Team |

CORTX-28628 - Remove python3-ldap package from cortx-rgw image

---

docker/cortx-deploy/build.sh
docker/cortx-deploy/generate-release-info.sh
scripts/release_support/changelog.sh

-  Added cortx-re githash in `org.opencontainers.image.revision` lable so that we can query https://github.com/Seagate/cortx-re githash used to build image. 
```
[root@ssc-vm-rhev4-0707 cortx-deploy]# docker inspect --format='{{ index .Config.Labels "org.opencontainers.image.revision"}}' cortx-rgw:2.0.0-5599
cortx-py-utils:89995d1, cortx-motr:319cc081, cortx-hare:929122f, cortx-provisioner:da8e4e7f, cortx-ha:7a5d356, cortx-rgw-integration:7e096ab, cortx-csm_agent:97ae8986, cortx-rgw:g281ff195aa7, cortx-re:842e668,
```

CORTX-31968 - Add cortx-re githash in CORTX image label

---

jenkins/performance-ci/nightly-performance-ci.groovy
jenkins/performance-ci/performance-sanity.groovy

- Add performance stats in the nightly email notification. Which can be further used to derive deviations. 

CORTX-31390 - Add performance stats in nightly performance-ci email notification

---

scripts/custom-iso/custom-packages.txt
scripts/deployment/roles/vm_deployment/templates/cortx_deploy_prereq.sh.j2
scripts/third-party-rpm/install-cortx-prereq.sh

Signed-off-by: Abhirup Ghosh <abhirup.ghosh@seagate.com>
- CORTX-31644 removed the java-1.8.0-openjdk
Didn't removed the below file as discussed with [Shailesh Vaidya](https://jts.seagate.com/secure/ViewProfile.jspa?name=729494)
In scripts/custom-prereq/kafka/kafka.spec
https://github.com/Seagate/cortx-re/blob/c124e0fc5fddbc619fb2a279cdc66dbd58b6fabe/scripts/custom-prereq/kafka/kafka.spec#L15
Didn't removed the below one as [Mukul Malhotra](https://jts.seagate.com/secure/ViewProfile.jspa?name=747271) has already Archived it >>[CORTX-31644: Old OVA code to Archive by mukul-seagate11 · Pull Request #1115 · Seagate/cortx-re (github.com)](https://github.com/Seagate/cortx-re/pull/1115)
In solution/ova/roles/vm-provisioner/files/provisioner.sh …

CORTX-31644 removed the java-1.8.0-openjdk

---

jenkins/internal-ci/generic/branch/release.groovy

- Disable wait for downstream 1N and 3N deployment jobs in Release pipeline due to known intermittent issue in 3N dpeloyment. 

CORTX-33837 - Disable wait for downstream 1N and 3N deployment jobs in Release pipeline

---

scripts/release_support/create-cortx-github-release.sh

- GitHub release script trying to fetch latest image id, which does not work if we need to release old image.
- Update `2.0.0-latest` tag to image tag which is getting released to fetch image id.

CORTX-34001: Fix logic to fetch image id for GitHub release

---

solutions/kubernetes/cortx-deploy-functions.sh

-  Modify resource limits as requested in CORTX-33977 .  Auto-generated solution.yaml is added below and is tested at - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/11522/artifact/artifacts/solution.yaml/*view*/
```
solution:
namespace: cortx
deployment_type: standard
secrets:
name: cortx-secret
content:
kafka_admin_secret: null
consul_admin_secret: null
common_admin_secret: null
s3_auth_admin_secret: ldapadmin
csm_auth_admin_secret: null
csm_mgmt_admin_secret: Cortxadmin@123
images:
consul: ghcr.io/seagate/consul:1.11.4
kafka: ghcr.io/seagate/kafka:3.0.0-debian-10-r97
zookeeper: ghcr.io/seagate/zookeeper:3.8.0-debian-10-r9
rancher: ghcr.io/seagate/local-path-provisioner:v0.0.20
busybox: ghcr.io/seagate/busybox:latest
cortxcontrol: …
```

CORTX-33977 Adapting Newly tuned Resource limit values in RE Deployment Job

---

.github/pr-title-checker-config.json
.github/workflows/pr-title-checker.yml

- pull request should contain JIRA ID or `COMMUNITY: ` at start of PR title. most of the times, developers do not follow this rule and main branch commit history does not look firm with commit messages which in turn do not generate good changelog.  
-  Setup a GitHub Action to check PR title for JIRA ID or `COMMUNITY: ` word. if not present, add failed label to PR.

CORTX-33968: Add GitHub Action pr-title-checker

---

jenkins/custom-ci/generic/custom-ci.groovy

- motr custom-ci link is broken
-  Fix broken link and build option for cortx-cc

CORTX-32167: Fix broken links in custom-ci

---

docker/cortx-deploy/cortx-all/cortx-component-rpms.txt
docker/cortx-deploy/cortx-data/cortx-component-rpms.txt
docker/cortx-deploy/cortx-rgw/cortx-component-rpms.txt

- cortx-cc component is not part of cortx-images
-  Add cortx-cc component in cortx images
custom-ci - https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/re-workspace/job/custom-ci-test/260/
image generation - https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/cortx-all-docker-image/2460/
deployment - https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/RGW/job/setup-cortx-rgw-cluster/12002/ 

CORTX-32167: Add cortx-cc in cortx images

---

solutions/kubernetes/cortx-deploy-functions.sh

- Added support for mandatory log device support in solution.yaml for DevOps CI/CD pipelines.  For standard VM specification following solution.yaml will be auto-generated
```
solution:
namespace: cortx
deployment_type: standard
secrets:
name: cortx-secret
content:
kafka_admin_secret: null
consul_admin_secret: null
common_admin_secret: null
s3_auth_admin_secret: ldapadmin
csm_auth_admin_secret: null
csm_mgmt_admin_secret: Cortxadmin@123
images:
consul: ghcr.io/seagate/consul:1.11.4
kafka: ghcr.io/seagate/kafka:3.0.0-debian-10-r97
zookeeper: ghcr.io/seagate/zookeeper:3.8.0-debian-10-r9
rancher: ghcr.io/seagate/local-path-provisioner:v0.0.20
busybox: ghcr.io/seagate/busybox:latest
cortxcontrol: ghcr.io/seagate/cortx-control:2.0.0-940
cortxdata: ghcr.io/seagate/cortx-data:2.0.0-940 …
```

CORTX-33243:  Add support for log device 

---

jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- We enabled DOCKER_BUILDKITas part of https://github.com/Seagate/cortx-re/pull/1220 to improve container image generation time.  
- DOCKER_BUILDKIT has disabled support for ContainerConfig. Refer  https://github.com/docker/cli/issues/2868
- We were using `ContainerConfig` in Nightly Deploy job to fetch Build URL details used in Nightly image creation. Refer - https://github.com/Seagate/cortx-re/blob/main/jenkins/internal-ci/generic/nightly/nightly-deploy.groovy#L101 .  Hence Nightly deploy job failed due to DOCKER_BUILDKIT change. 
- Disabled printing Build URL in Nightly Deploy. 
Checklist for …

CORTX-34239: Removed container image metadata fetch using ContainerConfig

---

scripts/performance/cortx-perfline.sh
solutions/community-deploy/CORTX-Deployment.md
solutions/kubernetes/cortx-deploy.sh
solutions/kubernetes/io-sanity.sh

- Add support for https://github.com/Seagate/cortx-k8s/releases/tag/v0.13.0

CORTX-34303: Add support for v0.13.0

---

jenkins/release-process/github-release.groovy
scripts/release_support/create-cortx-github-release.sh

- `-r` option in getopts was not getting called correctly in script `jenkins\release-process\github-release.groovy`
-  Updated script call 
-  Added non-zero check for `RELEASE_INFO` variable

CORTX-34001: Fix GitHub release process

---

jenkins/automation/kubernetes/setup-cortx-cluster.groovy
solutions/kubernetes/cortx-deploy-functions.sh
solutions/kubernetes/cortx-deploy.sh

- Deployment is failing due to HA POD not being in running a state within default timeout. Increased timeout from 240 sec to 480 sec for HA POD deployment to avoid deployment failures.

CORTX-34303: Set CORTX_DEPLOY_HA_TIMEOUT as 480s to avoid deployment failure. 

---

jenkins/automation/kubernetes/setup-cortx-cluster.groovy
jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- Addressed following nightly build issues - 
-  Skipped Sanity and Regression suite. 
-  Removed CORTX CICD <cortx-cicd@seagate.com> alias from failure email notification.
- Increased HA pod timeout to 10mins.

CORTX-34330: Nightly Build Issues

---

jenkins/internal-ci/generic/nightly/nightly-perfline-performance.groovy

- Disabled schedule from nightly-perfline-perf

CORTX-34342: Disabled schedule from nightly-perfline-perf

---

jenkins/automation/docker-image-ci.groovy
jenkins/internal-ci/generic/nightly/nightly-deploy.groovy

- Update nightly deploy email notification recipients
- Reduce frequency for CORTX Build Image Pipeline
https://eos-jenkins.colo.seagate.com/job/Release_Engineering/job/Cortx-Automation/job/docker-image-ci/ 
https://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/Nightly-K8s-Deploy/

CORTX-34342: Update nightly deploy email notification recipients and Reduce frequency for CORTX Build Image Pipeline

---

jenkins/internal-ci/generic/pr/cortx_deployment/pyutils.groovy

-  We have CORTX Utils Nightly Jenkins pipeline scheduled to execute on the main branch. Disabled scheduled execution and only keep PR-based execution. 

CORTX-34342: Removed schedule from utils PR pipeline

---

jenkins/automation/kubernetes/setup-cortx-cluster.groovy

- Deployment is failing with HA Pod timeout. Increased HA timeout value CORTX_DEPLOY_HA_TIMEOUT to 900s

CORTX-34390: Increased HA timeout value CORTX_DEPLOY_HA_TIMEOUT to 900s

---

docker/jenkins/prod_jenkins/docker-compose.yaml

-  Jenkins container image has a latest tag, so latest version get pulled every time which causes compatibility issue.
-  Internal volumes shifted to new NFS mount
-  Fetch Jenkins image from local private registry
-  Modify NFS mount details

CORTX-34403: Update Jenkins image and volumes

---

solutions/dashboard/build/build.sh
solutions/dashboard/build/docker-compose.yml
solutions/dashboard/build/logstash/Dockerfile
solutions/dashboard/build/logstash/Readme.md
solutions/dashboard/charts/dashboard-project/values.yaml
solutions/dashboard/config/logstash/LogstashCronjob.yaml
solutions/dashboard/deployment/dashboard/logstash.yaml

- Add support for logstash image generation in build.sh and docker-compose
- Modify the old logstash image name with the new one in the YAML files

CORTX-34425: Add support for logstash image generation

---

scripts/automation/alex/alex.py

- Date fetch is not working in alex python script
-  Fetching date using subprocess module

CORTX-34459: Alex script modification

---

jenkins/automation/vra_infra_provisioner.groovy

- VM provisioning through Jenkins pipeline https://eos-jenkins.colo.seagate.com/job/Cortx-Automation/job/VMware-Migration/job/provision-vm was failing.  
- IT team enabled terraform URLs in firewall 
- Infra team added Hasicorp repo locally 
- Infra team modified ssc-cicd-rocky88 as vmware catalog item

CORTX-34532: Use local repo for installing terraform
